[package]
name = "goldenscript"
description = "A scriptable, data-driven test framework using golden masters"
categories = ["development-tools::testing"]
version = "0.1.0"
authors = ["Erik Grinaker <erik@grinaker.org>"]
license = "Apache-2.0"
homepage = "https://github.com/erikgrinaker/goldenscript"
repository = "https://github.com/erikgrinaker/goldenscript"
edition = "2021"

[dependencies]
goldenfile = "1.7.1"
nom = "7.1.3"
nom_locate = "4.2.0"

[dev-dependencies]
chrono = "0.4.38"
dateparser = "0.2.1"
test_each_file = "0.3.2"
