//! Tests the `TryFrom` behavior generated by `#[derive(Command)]`.

#![warn(clippy::all)]

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::error::Error;
use std::str::FromStr;

use goldenscript::Command;

#[derive(Debug, PartialEq)]
struct Custom(u16);

impl FromStr for Custom {
    type Err = std::num::ParseIntError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        value.parse().map(Self)
    }
}

#[derive(Debug, PartialEq, Command)]
enum Scalars {
    Unit,
    #[command(name = "values")]
    Tuple(String, char, bool, i32, u64, f64, Custom),
    Struct {
        name: String,
        count: u8,
    },
}

#[derive(Debug, PartialEq, Command)]
enum Arguments {
    Values {
        required: String,
        optional: Option<u16>,
        rest: Vec<u16>,
        #[arg(key)]
        name: String,
        #[arg(key = "maybe")]
        optional_key: Option<u16>,
        properties: BTreeMap<String, u16>,
    },
    Sets {
        values: HashSet<u16>,
        properties: HashMap<String, u16>,
    },
    Ordered(BTreeSet<u16>),
    TupleKey(#[arg(key = "value")] u16),
    TupleMap(BTreeMap<String, u16>),
}

#[derive(Debug, PartialEq, Command)]
enum Metadata {
    RequiredPrefix {
        #[prefix]
        prefix: char,
    },
    OptionalPrefix(#[prefix] Option<u16>),
    IgnorePrefix,
    Tags {
        #[tag]
        fast: bool,
        #[tag(name = "verbose")]
        debug: bool,
    },
    AllTags {
        #[tag]
        fast: bool,
        #[tag]
        tags: Vec<String>,
    },
    HashTags {
        #[tag]
        tags: HashSet<String>,
    },
    TreeTags(#[tag] BTreeSet<String>),
}

/// Captures a parsed Goldenscript command through the public Runner API.
struct Capture(Option<Command>);

impl goldenscript::Runner for Capture {
    fn run(&mut self, command: &Command) -> Result<String, Box<dyn std::error::Error>> {
        self.0 = Some(command.clone());
        if command.fail { Err("expected failure".into()) } else { Ok(String::new()) }
    }
}

fn command(input: &str) -> Result<Command, Box<dyn Error>> {
    let mut capture = Capture(None);
    goldenscript::generate(&mut capture, &format!("{input}\n---\n"))?;
    capture.0.ok_or_else(|| "command was not run".into())
}

fn parse<T>(input: &str) -> Result<T, Box<dyn Error>>
where
    for<'a> T: TryFrom<&'a Command, Error = Box<dyn Error>>,
{
    T::try_from(&command(input)?)
}

#[test]
fn unit_tuple_struct_and_scalar_values() -> Result<(), Box<dyn Error>> {
    assert_eq!(parse::<Scalars>("unit")?, Scalars::Unit);
    assert_eq!(
        parse::<Scalars>(r#"values text x true "-12" 34 1.5 99"#)?,
        Scalars::Tuple("text".to_owned(), 'x', true, -12, 34, 1.5, Custom(99))
    );
    assert_eq!(
        parse::<Scalars>("struct alice 3")?,
        Scalars::Struct { name: "alice".to_owned(), count: 3 }
    );
    Ok(())
}

#[test]
fn required_optional_variadic_and_key_arguments() -> Result<(), Box<dyn Error>> {
    assert_eq!(
        parse::<Arguments>("values first 1 2 3 name=alice maybe=4 a=5 b=6 a=7")?,
        Arguments::Values {
            required: "first".to_owned(),
            optional: Some(1),
            rest: vec![2, 3],
            name: "alice".to_owned(),
            optional_key: Some(4),
            properties: BTreeMap::from([("a".to_owned(), 7), ("b".to_owned(), 6)]),
        }
    );
    assert_eq!(
        parse::<Arguments>("values first name=alice")?,
        Arguments::Values {
            required: "first".to_owned(),
            optional: None,
            rest: Vec::new(),
            name: "alice".to_owned(),
            optional_key: None,
            properties: BTreeMap::new(),
        }
    );
    Ok(())
}

#[test]
fn set_and_map_collections() -> Result<(), Box<dyn Error>> {
    assert_eq!(
        parse::<Arguments>("sets 3 1 3 a=1 b=2 a=4")?,
        Arguments::Sets {
            values: HashSet::from([1, 3]),
            properties: HashMap::from([("a".to_owned(), 4), ("b".to_owned(), 2)]),
        }
    );
    assert_eq!(
        parse::<Arguments>("ordered 3 1 2 1")?,
        Arguments::Ordered(BTreeSet::from([1, 2, 3]))
    );
    assert_eq!(parse::<Arguments>("tuple_key value=3 value=7")?, Arguments::TupleKey(7));
    assert_eq!(
        parse::<Arguments>("tuple_map a=1 b=2 a=3")?,
        Arguments::TupleMap(BTreeMap::from([("a".to_owned(), 3), ("b".to_owned(), 2)]))
    );
    Ok(())
}

#[test]
fn arguments_are_consumed_left_to_right_by_kind() -> Result<(), Box<dyn Error>> {
    assert_eq!(
        parse::<Arguments>("values first name=alice 1 maybe=2 3 a=4")?,
        Arguments::Values {
            required: "first".to_owned(),
            optional: Some(1),
            rest: vec![3],
            name: "alice".to_owned(),
            optional_key: Some(2),
            properties: BTreeMap::from([("a".to_owned(), 4)]),
        }
    );
    Ok(())
}

#[test]
fn prefixes_are_required_optional_or_ignored() -> Result<(), Box<dyn Error>> {
    assert_eq!(parse::<Metadata>("x: required_prefix")?, Metadata::RequiredPrefix { prefix: 'x' });
    assert_eq!(parse::<Metadata>("12: optional_prefix")?, Metadata::OptionalPrefix(Some(12)));
    assert_eq!(parse::<Metadata>("optional_prefix")?, Metadata::OptionalPrefix(None));
    assert_eq!(parse::<Metadata>("ignored: ignore_prefix")?, Metadata::IgnorePrefix);
    assert!(parse::<Metadata>("required_prefix").is_err());
    assert!(parse::<Metadata>("long: required_prefix").is_err());
    Ok(())
}

#[test]
fn named_and_collection_tags() -> Result<(), Box<dyn Error>> {
    assert_eq!(
        parse::<Metadata>("[fast,verbose] tags")?,
        Metadata::Tags { fast: true, debug: true }
    );
    assert_eq!(
        parse::<Metadata>("[fast,other] all_tags")?,
        Metadata::AllTags { fast: true, tags: vec!["fast".to_owned(), "other".to_owned()] }
    );
    assert_eq!(
        parse::<Metadata>("[b,a] hash_tags")?,
        Metadata::HashTags { tags: HashSet::from(["a".to_owned(), "b".to_owned()]) }
    );
    assert_eq!(
        parse::<Metadata>("[b,a] tree_tags")?,
        Metadata::TreeTags(BTreeSet::from(["a".to_owned(), "b".to_owned()]))
    );
    assert!(parse::<Metadata>("[unknown] tags").is_err());
    Ok(())
}

#[test]
fn conversion_errors() -> Result<(), Box<dyn Error>> {
    assert!(parse::<Scalars>("unknown").is_err());
    assert!(parse::<Scalars>("unit extra").is_err());
    assert!(parse::<Scalars>("struct only").is_err());
    assert!(parse::<Scalars>("struct name invalid").is_err());
    assert!(parse::<Scalars>(r#"values text xx true "-12" 34 1.5 99"#).is_err());
    Ok(())
}

#[test]
fn runner_flags_are_ignored() -> Result<(), Box<dyn Error>> {
    assert_eq!(parse::<Scalars>("(unit)")?, Scalars::Unit);
    assert_eq!(parse::<Scalars>("!unit")?, Scalars::Unit);
    Ok(())
}

#[test]
fn derive_ui() -> Result<(), Box<dyn Error>> {
    let tests = trybuild::TestCases::new();
    tests.pass("tests/derive/pass/*.rs");
    tests.compile_fail("tests/derive/fail/*.rs");
    Ok(())
}
