//! Tests the `TryFrom` behavior generated by `#[derive(Command)]`.

#![warn(clippy::all)]

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet, VecDeque};
use std::error::Error;
use std::num::ParseIntError;
use std::str::FromStr;

use goldenscript::Command;

// Type aliases, both generic and concrete.
type VecAlias<T> = Vec<T>;
type VecAliasU8 = Vec<u8>;

/// A custom type that implements FromStr.
#[derive(Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct Custom(u16);

impl FromStr for Custom {
    type Err = ParseIntError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        value.parse().map(Self)
    }
}

/// A custom container that implements FromIterator.
#[derive(Debug, PartialEq)]
struct CustomSet(HashSet<Custom>);

impl FromIterator<Custom> for CustomSet {
    fn from_iter<T: IntoIterator<Item = Custom>>(iter: T) -> Self {
        Self(iter.into_iter().collect())
    }
}

/// An enum with each variant shape.
#[derive(Command, Debug, PartialEq)]
enum Variants {
    Unit,
    Tuple(String, Vec<u8>),
    Struct { name: String, values: Vec<u8> },
}

/// An enum with various scalar values.
#[derive(Command, Debug, PartialEq)]
enum Scalars {
    String(String),
    Char(char),
    Bool(bool),
    I64(i64),
    U8(u8),
    F64(f64),
    Custom(Custom),
}

/// An enum with various container values.
#[derive(Command, Debug, PartialEq)]
enum Containers {
    #[command(name = "btree_map")]
    BTreeMap(BTreeMap<Custom, Custom>),
    #[command(name = "btree_set")]
    BTreeSet(BTreeSet<Custom>),
    CustomSet(#[arg(many)] CustomSet),
    HashMap(HashMap<Custom, Custom>),
    HashSet(HashSet<Custom>),
    Vec(Vec<Custom>),
    VecAlias(#[arg(many)] VecAlias<Custom>),
    VecAliasU8(#[arg(many)] VecAliasU8),
    VecDeque(VecDeque<Custom>),
    VecKeyValue(Vec<(Custom, Custom)>),
    Option(Option<Custom>),
}

/// Captures a parsed Goldenscript command through the public Runner API.
struct Capture(Option<Command>);

impl goldenscript::Runner for Capture {
    type Command = Command;

    fn run(
        &mut self,
        command: &Command,
        context: &goldenscript::Context,
    ) -> Result<String, Box<dyn Error>> {
        self.0 = Some(command.clone());
        if context.fail { Err("expected failure".into()) } else { Ok(String::new()) }
    }
}

fn command(input: &str) -> Result<Command, Box<dyn Error>> {
    let mut capture = Capture(None);
    goldenscript::generate(&mut capture, &format!("{input}\n---\n"))?;
    capture.0.ok_or_else(|| "command was not run".into())
}

fn parse<T>(input: &str) -> Result<T, Box<dyn Error>>
where
    for<'a> T: TryFrom<&'a Command, Error = Box<dyn Error>>,
{
    T::try_from(&command(input)?)
}

fn parse_error<T>(input: &str) -> String
where
    for<'a> T: TryFrom<&'a Command, Error = Box<dyn Error>>,
{
    match parse::<T>(input) {
        Ok(_) => panic!("expected conversion error"),
        Err(error) => error.to_string(),
    }
}

#[test]
fn variant_shapes() -> Result<(), Box<dyn Error>> {
    assert_eq!(parse::<Variants>("unit")?, Variants::Unit);
    assert_eq!(
        parse::<Variants>("tuple text 1 2 3")?,
        Variants::Tuple("text".to_owned(), vec![1, 2, 3])
    );
    assert_eq!(
        parse::<Variants>("struct alice 4 5 6")?,
        Variants::Struct { name: "alice".to_owned(), values: vec![4, 5, 6] }
    );
    Ok(())
}

#[test]
fn scalar_values() -> Result<(), Box<dyn Error>> {
    assert_eq!(parse::<Scalars>("string text")?, Scalars::String("text".to_owned()));
    assert_eq!(parse::<Scalars>("char x")?, Scalars::Char('x'));
    assert_eq!(parse::<Scalars>("bool true")?, Scalars::Bool(true));
    assert_eq!(parse::<Scalars>(r#"i64 "-12""#)?, Scalars::I64(-12));
    assert_eq!(parse::<Scalars>("u8 34")?, Scalars::U8(34));
    assert_eq!(parse::<Scalars>("f64 1.5")?, Scalars::F64(1.5));
    assert_eq!(parse::<Scalars>("custom 99")?, Scalars::Custom(Custom(99)));
    Ok(())
}

#[test]
fn scalar_conversion_errors() {
    assert_eq!(parse_error::<Scalars>("string"), "argument '1' not given");
    assert_eq!(
        parse_error::<Scalars>("char xx"),
        "invalid value 'xx' for argument '1': too many characters in string"
    );
    assert_eq!(
        parse_error::<Scalars>("bool invalid"),
        "invalid value 'invalid' for argument '1': provided string was not `true` or `false`"
    );
    assert_eq!(
        parse_error::<Scalars>("i64 invalid"),
        "invalid value 'invalid' for argument '1': invalid digit found in string"
    );
    assert_eq!(
        parse_error::<Scalars>("u8 invalid"),
        "invalid value 'invalid' for argument '1': invalid digit found in string"
    );
    assert_eq!(
        parse_error::<Scalars>("f64 invalid"),
        "invalid value 'invalid' for argument '1': invalid float literal"
    );
    assert_eq!(
        parse_error::<Scalars>("custom invalid"),
        "invalid value 'invalid' for argument '1': invalid digit found in string"
    );
}

#[test]
fn container_values() -> Result<(), Box<dyn Error>> {
    assert_eq!(
        parse::<Containers>("btree_map 1=3 2=2 1=1")?,
        Containers::BTreeMap(BTreeMap::from([(Custom(1), Custom(1)), (Custom(2), Custom(2)),]))
    );
    assert_eq!(
        parse::<Containers>("btree_set 3 1 2 1")?,
        Containers::BTreeSet(BTreeSet::from([Custom(1), Custom(2), Custom(3)]))
    );
    assert_eq!(
        parse::<Containers>("custom_set 3 1 2 1")?,
        Containers::CustomSet(CustomSet(HashSet::from([Custom(1), Custom(2), Custom(3)])))
    );
    assert_eq!(
        parse::<Containers>("hash_map 1=3 2=2 1=1")?,
        Containers::HashMap(HashMap::from([(Custom(1), Custom(1)), (Custom(2), Custom(2)),]))
    );
    assert_eq!(
        parse::<Containers>("hash_set 3 1 2 1")?,
        Containers::HashSet(HashSet::from([Custom(1), Custom(2), Custom(3)]))
    );
    assert_eq!(
        parse::<Containers>("vec 3 1 2")?,
        Containers::Vec(vec![Custom(3), Custom(1), Custom(2)])
    );
    assert_eq!(
        parse::<Containers>("vec_alias 3 1 2")?,
        Containers::VecAlias(vec![Custom(3), Custom(1), Custom(2)])
    );
    assert_eq!(parse::<Containers>("vec_alias_u8 3 1 2")?, Containers::VecAliasU8(vec![3, 1, 2]));
    assert_eq!(
        parse::<Containers>("vec_deque 3 1 2")?,
        Containers::VecDeque(VecDeque::from([Custom(3), Custom(1), Custom(2)]))
    );
    assert_eq!(
        parse::<Containers>("vec_key_value 3=1 1=2 3=1")?,
        Containers::VecKeyValue(vec![
            (Custom(3), Custom(1)),
            (Custom(1), Custom(2)),
            (Custom(3), Custom(1)),
        ])
    );
    assert_eq!(parse::<Containers>("option 3")?, Containers::Option(Some(Custom(3))));
    assert_eq!(parse::<Containers>("option")?, Containers::Option(None));
    Ok(())
}

#[test]
fn argument_kinds() -> Result<(), Box<dyn Error>> {
    #[derive(Command, Debug, PartialEq)]
    enum ArgumentKinds {
        Pos {
            inferred: String,
            #[arg(pos)]
            required: String,
            #[arg(pos)]
            optional: Option<usize>,
            #[arg(pos, optional)]
            default: usize,
            #[arg(pos, optional)]
            many: Vec<usize>,
        },
        Key {
            #[arg(key)]
            required: String,
            #[arg(key = "name")]
            alias: String,
            #[arg(key)]
            optional: Option<usize>,
            #[arg(key, optional)]
            default: usize,
            #[arg(key, optional)]
            many: HashMap<String, usize>,
        },
    }

    assert_eq!(
        parse::<ArgumentKinds>("pos first second 1 2 3 4")?,
        ArgumentKinds::Pos {
            inferred: "first".to_owned(),
            required: "second".to_owned(),
            optional: Some(1),
            default: 2,
            many: vec![3, 4],
        }
    );
    assert_eq!(
        parse::<ArgumentKinds>("pos first second")?,
        ArgumentKinds::Pos {
            inferred: "first".to_owned(),
            required: "second".to_owned(),
            optional: None,
            default: 0,
            many: Vec::new(),
        }
    );
    assert_eq!(
        parse::<ArgumentKinds>("key a=3 required=first b=4 name=second optional=1 default=2 a=5")?,
        ArgumentKinds::Key {
            required: "first".to_owned(),
            alias: "second".to_owned(),
            optional: Some(1),
            default: 2,
            many: HashMap::from([("a".to_owned(), 5), ("b".to_owned(), 4)]),
        }
    );
    assert_eq!(
        parse::<ArgumentKinds>("key required=first name=second")?,
        ArgumentKinds::Key {
            required: "first".to_owned(),
            alias: "second".to_owned(),
            optional: None,
            default: 0,
            many: HashMap::new(),
        }
    );
    assert_eq!(parse_error::<ArgumentKinds>("pos"), "argument 'inferred' not given");
    assert_eq!(
        parse_error::<ArgumentKinds>("pos first second invalid"),
        "invalid value 'invalid' for argument 'optional': invalid digit found in string"
    );
    assert_eq!(parse_error::<ArgumentKinds>("key name=second"), "argument 'required' not given");
    assert_eq!(
        parse_error::<ArgumentKinds>("key required=first name=second optional=invalid"),
        "invalid value 'invalid' for argument 'optional': invalid digit found in string"
    );
    Ok(())
}

#[test]
fn keyed_collection_conversion_errors() {
    assert_eq!(
        parse_error::<Containers>("hash_map invalid=1"),
        "invalid value 'invalid' for argument 'HashMap': invalid digit found in string"
    );
    assert_eq!(
        parse_error::<Containers>("hash_map 1=invalid"),
        "invalid value 'invalid' for argument 'HashMap': invalid digit found in string"
    );
}

#[test]
fn optional_defaults() -> Result<(), Box<dyn Error>> {
    #[derive(Command, Debug, PartialEq)]
    enum OptionalArguments {
        Values {
            #[arg(optional)]
            pos: u16,
            #[arg(key, optional)]
            key: u16,
        },
    }

    assert_eq!(parse::<OptionalArguments>("values")?, OptionalArguments::Values { pos: 0, key: 0 });
    assert_eq!(
        parse::<OptionalArguments>("values 3 key=4")?,
        OptionalArguments::Values { pos: 3, key: 4 }
    );
    Ok(())
}

#[test]
fn other_command() -> Result<(), Box<dyn Error>> {
    /// An enum with a fallback for unrecognized commands.
    #[derive(Command, Debug, PartialEq)]
    enum CommandsWithOther {
        Known,
        #[command(other)]
        Other(Command),
    }

    assert_eq!(parse::<CommandsWithOther>("known")?, CommandsWithOther::Known);

    let raw = command("unknown value key=7")?;
    assert_eq!(CommandsWithOther::try_from(&raw)?, CommandsWithOther::Other(raw));
    Ok(())
}

#[test]
fn fixed_key_uses_last_value_and_removes_all_matches() -> Result<(), Box<dyn Error>> {
    #[derive(Command, Debug, PartialEq)]
    enum FixedKeys {
        Tuple(#[arg(key = "value")] u16),
        ThenMap {
            #[arg(key = "selected")]
            selected: u16,
            #[arg(key, optional, many)]
            properties: BTreeMap<String, u16>,
        },
    }

    assert_eq!(parse::<FixedKeys>("tuple value=3 value=7")?, FixedKeys::Tuple(7));
    assert_eq!(
        parse::<FixedKeys>("then_map selected=1 a=2 selected=3")?,
        FixedKeys::ThenMap { selected: 3, properties: BTreeMap::from([("a".to_owned(), 2)]) }
    );
    Ok(())
}

#[test]
fn optional_key_can_precede_required_key() -> Result<(), Box<dyn Error>> {
    #[derive(Command, Debug, PartialEq)]
    enum KeyOrder {
        Values {
            #[arg(key)]
            optional: Option<u16>,
            #[arg(key)]
            required: u16,
        },
    }

    assert_eq!(
        parse::<KeyOrder>("values required=7")?,
        KeyOrder::Values { optional: None, required: 7 }
    );
    assert_eq!(
        parse::<KeyOrder>("values required=7 optional=3")?,
        KeyOrder::Values { optional: Some(3), required: 7 }
    );
    Ok(())
}

#[test]
fn many_field_can_be_followed_by_the_other_argument_kind() -> Result<(), Box<dyn Error>> {
    #[derive(Command, Debug, PartialEq)]
    enum MixedKinds {
        KeysFirst {
            keys: BTreeMap<String, usize>,
            value: usize,
            values: Vec<usize>,
        },
        ValuesFirst {
            values: Vec<usize>,
            #[arg(key)]
            key: String,
            keys: BTreeMap<String, usize>,
        },
    }

    assert_eq!(
        parse::<MixedKinds>("keys_first a=1 7 b=2 8")?,
        MixedKinds::KeysFirst {
            keys: BTreeMap::from([("a".to_owned(), 1), ("b".to_owned(), 2)]),
            value: 7,
            values: vec![8],
        }
    );
    assert_eq!(
        parse::<MixedKinds>("values_first key=value 7 a=1 b=2 8")?,
        MixedKinds::ValuesFirst {
            values: vec![7, 8],
            key: "value".to_string(),
            keys: BTreeMap::from([("a".to_owned(), 1), ("b".to_owned(), 2)]),
        }
    );
    Ok(())
}

#[test]
fn repeated_attributes_and_options_use_the_last_value() -> Result<(), Box<dyn Error>> {
    #[derive(Command, Debug, PartialEq)]
    enum RepeatedAttributes {
        #[command(name = "foo", name = "one")]
        CommandOptions,
        #[command(name = "foo")]
        #[command]
        #[command(name = "two")]
        CommandAttributes,
        ArgumentOptions {
            #[arg(key = "", key = "foo")]
            #[arg(key = "final")]
            value: u16,
        },
        DefaultArgumentKey {
            #[arg(key = "foo")]
            #[arg(key)]
            value: u16,
        },
        Positional {
            #[arg(pos, pos)]
            #[arg(pos)]
            value: u16,
        },
    }

    assert_eq!(parse::<RepeatedAttributes>("one")?, RepeatedAttributes::CommandOptions);
    assert_eq!(parse::<RepeatedAttributes>("two")?, RepeatedAttributes::CommandAttributes);
    assert_eq!(
        parse::<RepeatedAttributes>("argument_options final=7")?,
        RepeatedAttributes::ArgumentOptions { value: 7 }
    );
    assert_eq!(
        parse::<RepeatedAttributes>("default_argument_key value=8")?,
        RepeatedAttributes::DefaultArgumentKey { value: 8 }
    );
    assert_eq!(
        parse::<RepeatedAttributes>("positional 9")?,
        RepeatedAttributes::Positional { value: 9 }
    );
    Ok(())
}

#[test]
fn empty_names() -> Result<(), Box<dyn Error>> {
    #[derive(Command, Debug, PartialEq)]
    enum EmptyNames {
        #[command(name = "")]
        Values {
            #[arg(key = "")]
            value: String,
        },
    }

    assert_eq!(parse::<EmptyNames>(r#""" ""="""#)?, EmptyNames::Values { value: String::new() });
    Ok(())
}

#[test]
fn runner_metadata_is_ignored() -> Result<(), Box<dyn Error>> {
    assert_eq!(parse::<Variants>("(unit)")?, Variants::Unit);
    assert_eq!(parse::<Variants>("!unit")?, Variants::Unit);
    assert_eq!(parse::<Variants>("prefix:[tag] unit")?, Variants::Unit);
    Ok(())
}
