//! This crate provides the Goldenscript testing framework, loosely based on
//! Cockroach Labs' [`datadriven`](https://github.com/cockroachdb/datadriven)
//! framework for Go. It combines
//! [golden master](https://en.wikipedia.org/wiki/Characterization_test),
//! [data-driven](https://en.wikipedia.org/wiki/Data-driven_testing),
//! and [keyword-driven](https://en.wikipedia.org/wiki/Keyword-driven_testing)
//! testing.
//!
//! A goldenscript is a plain text file that contains a set of arbitrary
//! commands and their expected output, separated by `---`:
//!
//! ```yaml
//! command argument key=value
//! ---
//! output
//!
//! # Example testing a key/value store:
//! get foo
//! set foo=bar
//! get foo
//! ---
//! get foo → None
//! set foo=bar → new
//! get foo → 1
//! ```
//!
//! Commands are executed by a provided [`Runner`]. The expected output is not
//! written by hand, but generated by running the tests with
//! `UPDATE_GOLDENFILES=1` (via the
//! [`goldenfile`](https://docs.rs/goldenfile/latest/goldenfile/) crate):
//!
//! ```sh
//! $ UPDATE_GOLDENFILES=1 cargo test
//! ```
//!
//! The generated files are then verified by inspection and checked in to
//! version control. Tests will fail if their output does not match.
//!
//! This approach is particularly useful when testing complex stateful systems
//! such as databases, network servers, language parsers, etc. It can be tedious
//! and time-consuming to code test assertions by hand; writing scripts and
//! recording the expected behavior is often much more effective. And it's
//! usually straightforward to change assertions or behavior later: simply
//! regenerate the new output and inspect it.
//!
//! # Writing Tests
//!
//! To write tests using Goldenscript:
//!
//! 1. Design commands to use. Typically an enum with [`#[derive(Command)]`](derive@Command).
//! 2. Implement a [`Runner`] that executes the commands.
//! 3. Write a script file, with no expected output (yet).
//! 4. Write a Rust test that executes the script using the runner.
//! 5. Run `UPDATE_GOLDENFILES=1 cargo test` to generate output and review it.
//!
//! As a very simple example, add `tests/echo.rs`:
//!
//! ```no_run
//! #[derive(goldenscript::Command)]
//! enum Command {
//!     Echo(String),
//! }
//!
//! struct Runner;
//!
//! impl goldenscript::Runner for Runner {
//!     type Command = Command;
//!
//!     fn run(
//!         &mut self,
//!         command: &Self::Command,
//!         _context: &goldenscript::Context,
//!     ) -> Result<String, Box<dyn Error>> {
//!         let mut output = String::new();
//!         match command {
//!             Command::Echo(message) => writeln!(output, "{message}")?,
//!         }
//!         Ok(output)
//!     }
//! }
//!
//! #[test]
//! fn echo() -> std::io::Result<()> {
//!     goldenscript::run(&mut Runner, "tests/echo")
//! }
//! ```
//!
//! And a simple test script in `tests/echo`, with no expected output after `---`:
//!
//! ```
//! # echo should output its argument.
//! echo foo
//! ---
//!
//! # echo also supports multiple lines and Unicode.
//! echo "Hello!\n👋"
//! ---
//! ```
//!
//! Next, run the test with `UPDATE_GOLDENFILES=1` to generate the expected output:
//!
//! ```sh
//! $ UPDATE_GOLDENFILES=1 cargo test
//! ```
//!
//! Inspect the generated output in `tests/echo` to verify it:
//!
//! ```
//! # echo should output its argument.
//! echo foo
//! ---
//! foo
//!
//! # echo also supports multiple lines and Unicode.
//! echo "Hello!\n👋"
//! ---
//! Hello!
//! 👋
//! ```
//!
//! The output looks good, and we can commit the test to version control. The
//! next run will verify that the output matches the script:
//!
//! ```sh
//! $ cargo test
//! running 1 tests
//! test echo ... ok
//! ```
//!
//! For running all scripts in a directory, see [Testing Many Scripts](#testing-many-scripts).
//!
//! ## Deriving Commands
//!
//! [`#[derive(goldenscript::Command)]`](derive@Command) generates commands
//! based on an enum. The enum variants become commands and the variant fields
//! become arguments. Variants can be unit, tuple, or struct; unit variants
//! reject all arguments.
//!
//! The derive does this by implementing [`TryFrom<&Command>`](TryFrom) on the
//! enum, such that it can be used as a [`Runner::Command`] type.
//!
//! The `#[command]` and `#[arg]` attributes can be used on variants and fields
//! to modify command and argument behavior. These are optional, and the
//! defaults will be derived from the enum's structure. They are processed in
//! source order.
//!
//! This example illustraties various features:
//!
//! ```no_run
//! #[derive(goldenscript::Command)]
//! enum Command {
//!     /// Deletes a key. Example: delete foo
//!     Delete(
//!         // By default, arguments are positional and required.
//!         String,
//!     ),
//!
//!     /// Fetches a key. Example: get foo ignore_missing=true
//!     Get(
//!         String,
//!         // The #[arg] attribute can specify key/value arguments via `key`.
//!         // The key name can be given explicitly, or inferred from a struct
//!         // field name.
//!         //
//!         // Optional fields default to their `Default` value.
//!         //
//!         // Non-string arguments such as `bool` are parsed using `FromStr`.
//!         #[arg(key = "ignore_missing", optional)] bool,
//!     ),
//!
//!     /// Fetches many keys. Example: get_many foo bar baz
//!     GetMany(
//!         // Unary collection types take 1 or more positional arguments. 0 would
//!         // be allowed if given `optional`.
//!         Vec<String>,
//!     ),
//!
//!     /// Sets a key to a value. Example: set foo bar replace=false
//!     Set {
//!         // Struct fields are also positional arguments by default, not
//!         // key/value arguments.
//!         key: String,
//!         value: String,
//!         // `#[arg(key)]` makes this a key/value argument. The name is taken from
//!         // the field name by default, but can be aliased.
//!         #[arg(key, optional)]
//!         replace: bool,
//!     },
//!
//!     /// Sets many key/value pairs. Example: set_many foo=a bar=b baz=c
//!     SetMany(
//!         // Map types or `Vec<(K, V)>` take 1 or more key/value arguments.
//!         std::collections::HashMap<String, String>,
//!     ),
//!
//!     /// Lists key/value pairs in the range `[from, to)`. Example: scan bar foo limit=3
//!     Scan {
//!         // Option fields become optional by default.
//!         from: Option<String>,
//!         to: Option<String>,
//!         // They also work for key/value arguments. The inner type can also
//!         // be non-string, and will be parsed via `FromStr`.
//!         #[arg(key)]
//!         limit: Option<usize>,
//!     },
//! }
//! ```
//!
//! ### Commands: `#[command]`
//!
//! Each enum variant corresponds to a command. By default, its name becomes the
//! command name in `snake_case` form.
//!
//! The optional `#[command]` attribute can be used to specify:
//!
//! * `name = [name]`: specifies the command name. Must be unique within the
//!   enum.
//!
//! * `other`: makes the variant match any otherwise unknown command and is given
//!   the original raw [`struct@Command`]. This must be the last enum variant
//!   and have exactly one unnamed field of type [`struct@Command`].
//!
//! ### Arguments: `#[arg]`
//!
//! Each variant field corresponds to a command argument. They are processed in
//! declaration order, and consume the corresponding argument. By default,
//! arguments are positional and required.
//!
//! Field types must implement [`FromStr`](std::str::FromStr), with an error
//! that implements [`Display`](std::fmt::Display). However, the following
//! special type names infer additional default properties:
//!
//! * `Option<T>`: makes the argument optional, i.e. `#[arg(optional)]`.
//!
//! * `Vec<T>`, `VecDeque<T>`, `HashSet<T>`, `BTreeSet<T>`: takes one or more positional
//!   arguments, i.e. `#[arg(pos, many)]`.
//!
//! * `Vec<(K, V)>`, `HashMap<K, V>`, and `BTreeMap<K, V>`: takes one or more key/value
//!   arguments, i.e. `#[arg(key, many)]`).
//!
//! The optional `#[arg]` attribute can be used to specify:
//!
//! * `pos`: a positional argument. This is the default. Conflicts with `key`.
//!
//! * `key`: a key/value argument. Uses the field name as the key by default,
//!   but can be aliased as `key = [name]` (required for tuple fields). Key
//!   names must be unique within a variant. Conflicts with `pos`.
//!
//! * `optional`: allows the argument to be omitted, yielding the [`Default`]
//!   value.
//!
//! * `many`: consumes all remaining arguments of its kind (pos or key) using
//!   [`FromIterator`]. `pos` arguments must take type `T`, while `key`
//!   arguments must take `(K, V)`. At least one argument must be provided,
//!   unless `optional` is set.
//!
//! A required positional field cannot be specified after an optional positional
//! field. Fields with `many` must be the last field of the same argument kind
//! (`pos` or `key`), but can be followed by a field of the other kind.
//!
//! ## Implementing `Runner`
//!
//! A runner is used to execute commands. It must implement the [`Runner`] trait,
//! which at minimum requires specifying:
//!
//! * [`Runner::Command`]: the command type passed to the runner. This will
//!   typically be an enum using [`#[derive(Command)]`](struct@Command), but can
//!   also be a raw unprocessed [`struct@Command`], or any other type that
//!   implements [`TryFrom<&goldenscript::Command>`](TryFrom).
//!
//! * [`Runner::run`]: a method that takes a [`Runner::Command`] and its
//!   [`Context`], executes it, and returns
//!
//! A minimal runner implementation can be seen in the
//! [Writing Tests](#writing-tests) section.
//!
//! ### Hooks
//!
//! Runners have various hooks that are called during script execution:
//!
//! * [`Runner::start_script`]
//! * [`Runner::end_script`]
//! * [`Runner::start_block`],
//! * [`Runner::end_block`]
//! * [`Runner::start_command`]
//! * [`Runner::end_command`]
//!
//! These can be used e.g. for initial setup, invariant assertions, state dumps,
//! or other logic that's common across commands.
//!
//! These are sometimes combined with [tags](`Context::tags`) to control their
//! behavior from scripts across different commands.
//!
//! ### Manual Command Processing
//!
//! It may sometimes be useful to process raw a [`struct@Command`] instead of
//! using [`#[derive(Command)]`](derive@Command), for example when customized
//! processing is needed or in combination with `#[command(other)]` wildcards.
//!
//! In these cases, the arguments can be processed manually from
//! [`Command::args`], or using the [`ArgumentConsumer`] helper via
//! [`Command::consume_args()`]. For example:
//!
//! ```
//! # use std::error::Error;
//! struct Runner;
//!
//!
//! impl goldenscript::Runner for Runner {
//!     // Take a raw command.
//!     type Command = goldenscript::Command;
//!
//!     fn run(
//!         &mut self,
//!         command: &goldenscript::Command,
//!         _context: &goldenscript::Context,
//!     ) -> Result<String, Box<dyn Error>> {
//!         let mut output = String::new();
//!         match command.name.as_str() {
//!             // Sends a string message to a list of nodes.
//!             //
//!             // Usage:   send [retry=BOOL] MESSAGE ID...
//!             // Example: send foo 1 2 3
//!             "send" => {
//!                 let mut args = command.consume_args();
//!        
//!                 // The first positional argument is a required string message.
//!                 let message = args.next_pos().ok_or("message not given")?;
//!        
//!                 // The remaining positional arguments are numeric node IDs.
//!                 let ids: Vec<u32> = std::iter::from_fn(|| args.next_pos())
//!                     .map(|value| value.parse())
//!                     .collect::<Result<_, _>>()?;
//!                 if ids.is_empty() {
//!                     return Err("no node IDs given".into())
//!                 }
//!        
//!                 // An optional retry=bool key/value argument can also be given.
//!                 let retry: bool =
//!                     args.take_key("retry").map(|v| v.parse()).transpose()?.unwrap_or(false);
//!        
//!                 // Any other arguments that haven't been processed above should error.
//!                 args.reject_next()?;
//!        
//!                 // Execute the send.
//!                 self.send(&ids, message, retry)?;
//!             }
//!             name => return Err(format!("invalid command {name}").into())
//!         }
//!         Ok(output)
//!     }
//! }
//!
//! impl Runner {
//!   fn send(&self, ids: &[u32], message: &str, retry: bool) -> Result<(), Box<dyn Error>> {
//!     unimplemented!();
//!   }
//! }
//! ```
//!
//! ### Managing State
//!
//! The runner can manage internal state however it wants to. However, it is
//! recommended to instantiate a new runner for every goldenscript, such that
//! it is self-contained and discoverable. Otherwise, tests will e.g. rely on
//! the execution order of different scripts.
//!
//! Initial state setup should generally be done via explicit setup commands in
//! the scripts, to make it more discoverable. For complex state, it may also be
//! helpful to output the state in scripts at various points, either with
//! explicit commands or after each command/block via hooks.
//!
//! ## Testing Many Scripts
//!
//! It's often convenient to automatically generate individual Rust tests for
//! each goldenscript in a directory. This can be done with external crates such
//! as [`test_each_file`](https://docs.rs/test_each_file/latest/test_each_file/):
//!
//! ```no_run
//! # use std::error::Error;
//! # struct Runner;
//! # impl goldenscript::Runner for Runner {
//! #     type Command = goldenscript::Command;
//! #     fn run(
//! #         &mut self,
//! #         _command: &goldenscript::Command,
//! #         _context: &goldenscript::Context,
//! #     ) -> Result<String, Box<dyn Error>> { unimplemented!() }
//! # }
//! use test_each_file::test_each_path;
//!
//! test_each_path! { in "tests/scripts" as scripts => test_goldenscript }
//!
//! fn test_goldenscript(path: &std::path::Path) {
//!     goldenscript::run(&mut Runner, path).unwrap()
//! }
//! ```
//!
//! # Script Syntax
//!
//! This section describes the syntax used in goldenscripts. It is parsed into a
//! [`struct@Command`].
//!
//! ## Blocks
//!
//! A goldenscript consists of one or more input/output blocks. Each block has a
//! set of one or more input commands on individual lines (empty or comment
//! lines are ignored), a `---` separator, and arbitrary output terminated by an
//! empty line. A minimal goldenscript with two blocks might be:
//!
//! ```text
//! command
//! ---
//! output
//!
//! command 1
//! command 2
//! ---
//! output 1
//! output 2
//! ```
//!
//! ## Commands
//!
//! A [`struct@Command`] must have a command name, which can be any arbitrary
//! [string](#strings), e.g.:
//!
//! ```text
//! command
//! "command with space and 🚀"
//! ---
//! ```
//!
//! It may additionally have:
//!
//! * [**Arguments:**](Argument) any number of space-separated arguments.
//!   [Positional][`Argument::Positional`] arguments contain a value, while
//!   [key/value](`Argument::KeyValue`) arguments contain a key/value pair
//!   written as `key=value`. Argument values and keys can be empty strings,
//!   and duplicate keys are allowed (the runner can handle this as desired).
//!
//!     ```text
//!     command argument key=value
//!     command "argument with space" "key with space"="value with space"
//!     command "" key=  # Empty argument values.
//!     ---
//!     ```
//!
//! * [**Prefix:**](Context::prefix) an optional `:`-terminated string prefix
//!   before the command. The command's output will be given the same prefix.
//!   The prefix can be used by the test runner if desired, e.g. to
//!   differentiate two different client sessions.
//!
//!     ```text
//!     client1: put key=value
//!     client2: get key
//!     ---
//!     client1: put ok
//!     client2: get key=value
//!     ```
//!
//! * [**Silencing:**](Context::silent) a command wrapped in `()` will have its
//!   output suppressed. This can be useful e.g. for setup commands whose output
//!   is not relevant for a test case and only adds noise.
//!
//!     ```text
//!     echo foo
//!     (echo bar)
//!     ---
//!     foo
//!     ```
//!
//! * [**Failure:**](Context::fail) if `!` precedes the command, it is expected
//!   to fail with an error or panic. The failure message is used as output. If
//!   the command succeeds, the test fails. If the line contains other symbols
//!   before the command name (e.g. a prefix or silencing), the `!` must be used
//!   immediately before the command name.
//!
//!     ```text
//!     !command error=foo
//!     ---
//!     Error: foo
//!
//!     prefix: !command panic=bar
//!     (!command error=foo)
//!     ---
//!     prefix: Panic: bar
//!     ```
//!
//! * [**Tags:**](Context::tags) an optional comma- or space-separated list of
//!   strings enclosed in [] before or after the command and arguments. This can
//!   be used by the runner, e.g. for common options used across many commands.
//!
//!     ```text
//!     command [verbose]
//!     command arg key=value [a,b c]
//!     [verbose] command
//!     prefix:[tag]!> command arg
//!     ---
//!     ```
//!
//!  * **Literal:** if `>` precedes the command, the entire rest of the line is
//!    taken to be the command name (except leading whitespace). Arguments,
//!    tags, comments, and any other special characters are ignored and used
//!    as-is. As a special case (currently only with `>`), lines can span
//!    multiple lines by ending the line with \\.
//!
//!    ```text
//!    > a long command name including key=value, [tags], # a comment and exclamation!
//!    prefix: [tag] ! > a long, failing command with tags and a prefix
//!    ---
//!
//!    > a very \
//!    long command \
//!    with line \
//!    continuation
//!    ---
//!    ```
//!
//! ## Comments
//!
//! Comments begin with `#` or `//` and run to the end of the line.
//!
//! ```text
//! # This is a comment.
//! // As is this.
//! command argument # Comments can follow commands too.
//! ---
//! ```
//!
//!
//! ## Output
//!
//! The command output following a `---` separator can contain any arbitrary
//! Unicode string until an empty line (or end of file). If the command output
//! contains empty lines, the entire generated output will automatically be
//! prefixed with `> `. If no commands in a block yield any output, it defaults
//! to "ok".
//!
//! ```text
//! echo "output 1"
//! echo "output 2"
//! ---
//! output 1
//! output 2
//!
//! echo "Paragraph 1.\n\nParagraph 2."
//! ---
//! > Paragraph 1.
//! >
//! > Paragraph 2.
//!
//! echo "输出\n# Comment\n🚀"
//! ---
//! 输出
//! # Comment
//! 🚀
//! ```
//!
//! ## Strings
//!
//! Unquoted strings can only contain alphanumeric ASCII characters
//! `[a-zA-Z0-9]` and a handful of special characters: `_ - . / @`
//! (only `_` at the start of a string).
//!
//! Strings can be quoted using `"` or `'`, in which case they can contain
//! arbitrary Unicode characters. `\` is used as an escape character, both to
//! escape quotes `\"` and `\'` as well as itself `\\`, and also `\0` (null),
//! `\n` (newline), `\r` (carriage return), and `\t` (tab). `\x` can be used to
//! represent arbitrary hexadecimal bytes (e.g. `\x7a`) and `\u{}` can be used
//! to represent arbitrary Unicode characters (e.g. `\u{1f44b}`)
//!
//! ```text
//! string
//! "string with spaces and \"quotes\""
//! '字符串'
//! ---
//! ```
//!
//!
//! # Examples
//!
//! For actual usage examples, see e.g.:
//!
//! * [toyDB Raft](https://github.com/erikgrinaker/toydb/tree/master/src/raft/testscripts/node):
//!   distributed consensus implementation.
//! * [toyDB MVCC](https://github.com/erikgrinaker/toydb/tree/master/src/storage/testscripts/mvcc):
//!   ACID transaction implementation.
//! * [goldenscript parser](https://github.com/erikgrinaker/goldenscript/tree/main/tests/scripts):
//!   Goldenscript is used to test its own parser.
//!
//! Below is a basic example testing the Rust standard library's
//! [`BTreeMap`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html):
//!
//! ```yaml
//! # Tests the Rust standard library BTreeMap.
//!
//! # Range returns nothing for an empty map.
//! range
//! ---
//! range Unbounded → Unbounded
//!
//! # Insert a few keys out of order.
//! insert b=2 a=1 c=3
//! ---
//! insert "b" = "2" (was None)
//! insert "a" = "1" (was None)
//! insert "c" = "3" (was None)
//!
//! # Range emits them in order.
//! range
//! ---
//! range Unbounded → Unbounded
//! "a" = "1"
//! "b" = "2"
//! "c" = "3"
//!
//! # Getting a key returns its value, or None for missing keys.
//! get b
//! get foo
//! ---
//! get "b" → Some("2")
//! get "foo" → None
//!
//! # Bounded scans, where the end is exclusive.
//! range from=b
//! ---
//! range Included("b") → Unbounded
//! "b" = "2"
//! "c" = "3"
//!
//! range to=c
//! ---
//! range Unbounded → Excluded("c")
//! "a" = "1"
//! "b" = "2"
//!
//! range from=b to=c
//! ---
//! range Included("b") → Excluded("c")
//! "b" = "2"
//!
//! # An end bound less than the start bound panics. Expect the failure with !.
//! !range from=b to=a
//! ---
//! Panic: range start is greater than range end in BTreeMap
//!
//! # Replacing a key updates the value and returns the old one.
//! insert b=foo
//! get b
//! ---
//! insert "b" = "foo" (was Some("2"))
//! get "b" → Some("foo")
//! ```
//!
//! The corresponding runner for this script is implemented as:
//!
//! ```no_run
//! use std::collections::BTreeMap;
//! # use std::error::Error;
//! # use std::fmt::Write as _;
//!
//! /// Derive a command parser for an enum.
//! #[derive(goldenscript::Command)]
//! enum BTreeMapCommand {
//!     /// Fetches the given keys.
//!     Get(Vec<String>),
//!     /// Inserts the given key/value pairs.
//!     Insert(Vec<(String, String)>),
//!     /// Scans the given [from, to) range.
//!     Range {
//!         #[arg(key)]
//!         from: Option<String>,
//!         #[arg(key)]
//!         to: Option<String>,
//!     },
//! }
//!
//! /// Runner for the BTreeMap tests.
//! #[derive(Default)]
//! struct BTreeMapRunner {
//!     map: BTreeMap<String, String>,
//! }
//!
//! impl goldenscript::Runner for BTreeMapRunner {
//!     type Command = BTreeMapCommand;
//!
//!     fn run(
//!         &mut self,
//!         command: &BTreeMapCommand,
//!         _: &goldenscript::Context,
//!     ) -> Result<String, Box<dyn Error>> {
//!         let mut output = String::new();
//!         match command {
//!             BTreeMapCommand::Get(keys) => {
//!                 for key in keys {
//!                     let value = self.map.get(key);
//!                     writeln!(output, "get {key:?} → {value:?}")?;
//!                 }
//!             }
//!
//!             BTreeMapCommand::Insert(entries) => {
//!                 for (key, value) in entries {
//!                     let old = self.map.insert(key.clone(), value.clone());
//!                     writeln!(output, "insert {key:?} = {value:?} (was {old:?})")?;
//!                 }
//!             }
//!
//!             BTreeMapCommand::Range { from, to } => {
//!                 use std::ops::Bound;
//!                 let from = from.clone().map(Bound::Included).unwrap_or(Bound::Unbounded);
//!                 let to = to.clone().map(Bound::Excluded).unwrap_or(Bound::Unbounded);
//!                 writeln!(output, "range {from:?} → {to:?}")?;
//!                 for (key, value) in self.map.range((from, to)) {
//!                     writeln!(output, "{key:?} = {value:?}")?;
//!                 }
//!             }
//!         };
//!         Ok(output)
//!     }
//! }
//!
//! /// Run the test script in tests/btreemap.
//! #[test]
//! fn btreemap() -> std::io::Result<()> {
//!     goldenscript::run(&mut BTreeMapRunner::default(), "tests/btreemap")
//! }
//! ```

#![warn(clippy::all)]

mod command;
mod parser;
mod runner;

pub use command::{Argument, ArgumentConsumer, Block, Command, Context};
pub use goldenscript_macros::Command;
pub use runner::{Runner, generate, run};
