//! This crate provides the Goldenscript testing framework, loosely based on
//! Cockroach Labs' [`datadriven`](https://github.com/cockroachdb/datadriven)
//! framework for Go. It combines several testing techniques that make it easy
//! and efficient to write and update test cases:
//!
//! * [Golden master testing](https://en.wikipedia.org/wiki/Characterization_test)
//!   (aka characterization testing or historical oracle)
//! * [Data-driven testing](https://en.wikipedia.org/wiki/Data-driven_testing)
//!   (aka table-driven testing or parameterized testing)
//! * [Keyword-driven testing](https://en.wikipedia.org/wiki/Keyword-driven_testing)
//!
//! A goldenscript is a plain text file that contains a set of arbitrary input
//! commands and their expected text output, separated by `---`:
//!
//! ```text
//! command
//! ---
//! output
//!
//! command argument
//! command key=value
//! ---
//! output
//! ```
//!
//! The commands are executed by a provided [`Runner`]. The expected output is
//! usually not written by hand, but instead generated by running tests with the
//! environment variable `UPDATE_GOLDENFILES=1`:
//!
//! ```sh
//! $ UPDATE_GOLDENFILES=1 cargo test
//! ```
//!
//! The files are then verified by inspection and checked in to version control.
//! Tests will fail with a diff if they don't match the expected output.
//!
//! This approach is particularly useful when testing complex stateful systems,
//! such as database operations, network protocols, or language parsing. It can
//! be tedious and labor-intensive to write and assert such cases by hand, so
//! scripting and recording these interactions often yields much better test
//! coverage at a fraction of the cost.
//!
//! Internally, the
//! [`goldenfile`](https://docs.rs/goldenfile/latest/goldenfile/) crate is used
//! to manage golden files.
//!
//! # Examples
//!
//! For real-world examples, see e.g.:
//!
//! * [toyDB Raft](https://github.com/erikgrinaker/toydb/tree/master/src/raft/testscripts/node):
//!   distributed consensus cluster.
//! * [toyDB MVCC](https://github.com/erikgrinaker/toydb/tree/master/src/storage/testscripts/mvcc):
//!   ACID transactions.
//! * [goldenscript parser](https://github.com/erikgrinaker/goldenscript/tree/main/tests/scripts):
//!   Goldenscript uses itself to test its parser and runner.
//!
//! Below is a basic example, testing the Rust standard library's
//! [`BTreeMap`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html).
//!
//! ```yaml
//! # Tests the Rust standard library BTreeMap.
//!
//! # Range returns nothing for an empty map.
//! range
//! ---
//! range Unbounded → Unbounded
//!
//! # Insert a few keys out of order.
//! insert b=2 a=1 c=3
//! ---
//! insert "b" = "2" (was None)
//! insert "a" = "1" (was None)
//! insert "c" = "3" (was None)
//!
//! # Range emits them in order.
//! range
//! ---
//! range Unbounded → Unbounded
//! "a" = "1"
//! "b" = "2"
//! "c" = "3"
//!
//! # Getting a key returns its value, or None for missing keys.
//! get b
//! get foo
//! ---
//! get "b" → Some("2")
//! get "foo" → None
//!
//! # Bounded scans, where the end is exclusive.
//! range from=b
//! ---
//! range Included("b") → Unbounded
//! "b" = "2"
//! "c" = "3"
//!
//! range to=c
//! ---
//! range Unbounded → Excluded("c")
//! "a" = "1"
//! "b" = "2"
//!
//! # An end bound less than the start bound panics. Expect the failure with !.
//! !range from=b to=a
//! ---
//! Panic: range start is greater than range end in BTreeMap
//!
//! # Replacing a key updates the value and returns the old one.
//! insert b=foo
//! get b
//! ---
//! insert "b" = "foo" (was Some("2"))
//! get "b" → Some("foo")
//! ```
//!
//! The corresponding runner for this script:
//!
//! ```no_run
//! use std::collections::BTreeMap;
//! # use std::error::Error;
//! # use std::fmt::Write as _;
//! /// Commands accepted by BTreeMapRunner.
//! #[derive(goldenscript::Command)]
//! enum BTreeMapCommand {
//!     /// Fetches the given keys.
//!     Get(Vec<String>),
//!     /// Inserts the given key/value pairs.
//!     Insert(Vec<(String, String)>),
//!     /// Scans the given [from, to) range.
//!     Range {
//!         #[arg(key)]
//!         from: Option<String>,
//!         #[arg(key)]
//!         to: Option<String>,
//!     },
//! }
//!
//! /// A runner for BTreeMap tests. This is used as a documentation example.
//! #[derive(Default)]
//! struct BTreeMapRunner {
//!     map: BTreeMap<String, String>,
//! }
//!
//! impl goldenscript::Runner for BTreeMapRunner {
//!     type Command = BTreeMapCommand;
//!
//!     fn run(
//!         &mut self,
//!         command: &BTreeMapCommand,
//!         _: &goldenscript::Context,
//!     ) -> Result<String, Box<dyn Error>> {
//!         let mut output = String::new();
//!         match command {
//!             BTreeMapCommand::Get(keys) => {
//!                 for key in keys {
//!                     let value = self.map.get(key);
//!                     writeln!(output, "get {key:?} → {value:?}")?;
//!                 }
//!             }
//!
//!             BTreeMapCommand::Insert(entries) => {
//!                 for (key, value) in entries {
//!                     let old = self.map.insert(key.clone(), value.clone());
//!                     writeln!(output, "insert {key:?} = {value:?} (was {old:?})")?;
//!                 }
//!             }
//!
//!             BTreeMapCommand::Range { from, to } => {
//!                 use std::ops::Bound::*;
//!                 let from = from.clone().map(Included).unwrap_or(Unbounded);
//!                 let to = to.clone().map(Excluded).unwrap_or(Unbounded);
//!                 writeln!(output, "range {from:?} → {to:?}")?;
//!                 for (key, value) in self.map.range((from, to)) {
//!                     writeln!(output, "{key:?} = {value:?}")?;
//!                 }
//!             }
//!         };
//!         Ok(output)
//!     }
//! }
//!
//! #[test]
//! fn btreemap() {
//!     goldenscript::run(&mut BTreeMapRunner::default(), "tests/btreemap")
//!         .expect("goldenscript failed")
//! }
//! ```
//!
//! # Syntax
//!
//! ## Blocks
//!
//! A goldenscript consists of one or more input/output blocks. Each block has a
//! set of one or more input commands on individual lines (empty or comment
//! lines are ignored), a `---` separator, and arbitrary output terminated by an
//! empty line. A minimal goldenscript with two blocks might be:
//!
//! ```text
//! command
//! ---
//! output
//!
//! command 1
//! command 2
//! ---
//! output 1
//! output 2
//! ```
//!
//! ## Commands
//!
//! A [`struct@Command`] must have a command name, which can be any arbitrary
//! [string](#strings), e.g.:
//!
//! ```text
//! command
//! "command with space and 🚀"
//! ---
//! ```
//!
//! It may additionally have:
//!
//! * [**Arguments:**](Argument) any number of space-separated arguments.
//!   [`Argument::Positional`] arguments contain a value, while
//!   [`Argument::KeyValue`] arguments contain a key and value written as
//!   `key=value`. Keys and values can be empty, and duplicate keys are allowed
//!   by the parser (the runner can handle this as desired).
//!
//!     ```text
//!     command argument key=value
//!     command "argument with space" "key with space"="value with space"
//!     command "" key=  # Empty argument values.
//!     ---
//!     ```
//!
//! * [**Prefix:**](Context::prefix) an optional :-terminated string prefix
//!   before the command. The command's output will be given the same prefix.
//!   The prefix can be used by the test runner, e.g. to signify two different
//!   clients.
//!
//!     ```text
//!     client1: put key=value
//!     client2: get key
//!     ---
//!     client1: put ok
//!     client2: get key=value
//!     ```
//!
//! * [**Silencing:**](Context::silent) a command wrapped in `()` will have its
//!   output suppressed. This can be useful e.g. for setup commands whose output
//!   are not of interest in the current test case and would only add noise.
//!
//!     ```text
//!     echo foo
//!     (echo bar)
//!     ---
//!     foo
//!     ```
//!
//! * [**Failure:**](Context::fail) if `!` precedes the command, it is expected
//!   to fail with an error or panic, and the failure message is used as output.
//!   If the command unexpectedly succeeds, the test fails. If the line contains
//!   other symbols before the command name (e.g. a prefix or silencing), the
//!   `!` must be used immediately before the command name.
//!
//!     ```text
//!     ! command error=foo
//!     prefix: ! command panic=bar
//!     (!command error=foo)
//!     ---
//!     Error: foo
//!     prefix: Panic: bar
//!     ```
//!
//! * [**Tags:**](Context::tags) an optional comma- or space-separated list of
//!   tags (strings) enclosed in [] before or after the command and arguments.
//!   This can be used by the runner e.g. to modify the execution of a command.
//!
//!     ```text
//!     command [tag]
//!     command arg key=value [a,b c]
//!     [tag] command
//!     prefix:[tag]!> command arg
//!     ---
//!     ```
//!
//!  * **Literal:** if `>` precedes the command, the entire rest of the line is
//!    taken to be the command name (except leading whitespace). Arguments,
//!    tags, comments, and any other special characters are ignored and used
//!    as-is. As a special case (currently only with `>`), lines can span
//!    multiple lines by ending the line with \.
//!
//!    ```text
//!    > a long command name including key=value, [tags], # a comment and exclamation!
//!    prefix: [tag] ! > a long, failing command with tags and a prefix
//!    ---
//!
//!    > a very \
//!    long line \
//!    with line \
//!    continuation
//!    ---
//!    ```
//!
//! ## Output
//!
//! The command output following a `---` separator can contain any arbitrary
//! Unicode string until an empty line (or end of file). If the command output
//! contains empty lines, the entire output will automatically be prefixed with
//! `> `. If no commands in a block yield any output, it defaults to "ok".
//!
//! ```text
//! echo "output 1"
//! echo "output 2"
//! ---
//! output 1
//! output 2
//!
//! echo "Paragraph 1.\n\nParagraph 2."
//! ---
//! > Paragraph 1.
//! >
//! > Paragraph 2.
//!
//! echo "输出\n# Comment\n🚀"
//! ---
//! 输出
//! # Comment
//! 🚀
//! ```
//!
//! ## Comments
//!
//! Comments begin with `#` or `//` and run to the end of the line.
//!
//! ```text
//! # This is a comment.
//! // As is this.
//! command argument # Comments can follow commands too.
//! ---
//! ```
//!
//! ## Strings
//!
//! Unquoted strings can only contain alphanumeric ASCII characters
//! `[a-zA-Z0-9]` and a handful of special characters: `_ - . / @`
//! (only `_` at the start of a string).
//!
//! Strings can be quoted using `"` or `'`, in which case they can contain
//! arbitrary Unicode characters. `\` is used as an escape character, both to
//! escape quotes `\"` and `\'` as well as itself `\\`, and also `\0` (null),
//! `\n` (newline), `\r` (carriage return), and `\t` (tab). `\x` can be used to
//! represent arbitrary hexadecimal bytes (e.g. `\x7a`) and `\u{}` can be used
//! to represent arbitrary Unicode characters (e.g. `\u{1f44b}`)
//!
//! ```text
//! string
//! "string with spaces and \"quotes\""
//! '字符串'
//! ---
//! ```
//!
//! # Writing Tests
//!
//! In the simplest case, a goldenscript test might be:
//!
//! ```no_run
//! # use std::error::Error;
//! struct Runner;
//!
//! impl goldenscript::Runner for Runner {
//!     type Command = goldenscript::Command;
//!
//!     fn run(
//!         &mut self,
//!         command: &goldenscript::Command,
//!         _context: &goldenscript::Context,
//!     ) -> Result<String, Box<dyn Error>> {
//!         match command.name.as_str() {
//!             "echo" => {
//!                 let mut values = Vec::with_capacity(command.args.len());
//!                 for arg in &command.args {
//!                     match arg {
//!                         goldenscript::Argument::Positional(value) => values.push(value.as_str()),
//!                         _ => return Err(format!("invalid echo arg: {arg}").into()),
//!                     }
//!                 }
//!                 Ok(values.join("\n"))
//!             }
//!             name => return Err(format!("invalid command {name}").into())
//!         }
//!     }
//! }
//!
//! #[test]
//! fn test() -> std::io::Result<()> {
//!     goldenscript::run(&mut Runner, "tests/scripts/test")
//! }
//! ```
//!
//! ## Deriving Commands
//!
//! `#[derive(goldenscript::Command)]` implements [`TryFrom<&Command>`](TryFrom)
//! for an enum, allowing it to be used as a runner's [`Runner::Command`] type:
//!
//! ```rust
//! #[derive(goldenscript::Command)]
//! enum Command {
//!     /// Deletes a key. Example:
//!     /// delete foo ignore_missing=true
//!     Delete {
//!         // By default, arguments are positional and required.
//!         key: String,
//!         // The #[arg] attribute can specify keyed and/or optional arguments.
//!         #[arg(key, optional)]
//!         ignore_missing: bool,
//!     },
//!     /// Fetches a key. Example:
//!     /// get foo
//!     Get {
//!         key: String,
//!     },
//!     /// Fetches many keys. Can give 0 keys. Example:
//!     /// get_many foo bar baz
//!     GetMany(#[arg(optional)] Vec<String>),
//!     /// Sets a key to a value. Example:
//!     /// set foo bar replace=false
//!     Set {
//!         key: String,
//!         value: String,
//!         #[arg(key, optional)]
//!         replace: bool,
//!     },
//!     /// Sets many key/value pairs. Example:
//!     /// set_many foo=a bar=b baz=c
//!     SetMany(Vec<(String, String)>),
//!     /// Lists keys in the range [from, to). Example:
//!     /// scan bar foo limit=3
//!     Scan {
//!         from: Option<String>,
//!         to: Option<String>,
//!         #[arg(key)]
//!         limit: Option<usize>,
//!         #[arg(key, optional)]
//!         reverse: bool,
//!     },
//! }
//!
//! struct Runner;
//! impl goldenscript::Runner for Runner {
//!     type Command = Command;
//!
//!     fn run(
//!         &mut self,
//!         _command: &Command,
//!         _context: &goldenscript::Context,
//!     ) -> Result<String, Box<dyn std::error::Error>> {
//!        Ok(String::new())
//!     }
//! }
//! ```
//!
//! Helper attributes and their options are processed in source order.
//!
//! ### Commands: `#[command]`
//!
//! Each enum variant corresponds to a command. By default, its identifier is
//! converted to `snake_case` for the command name (e.g. `HTTPRequest` becomes
//! `http_request` and `GetURLValue` becomes `get_url_value`).
//!
//! The optional `#[command]` helper attribute accepts:
//!
//! * `name = "name"`: overrides the command name. The name can be empty, but
//!   resolved command names must be unique within the enum.
//!
//! * `other`: makes the variant match any otherwise unknown command and passes
//!   it the original raw [`struct@Command`]. This must be the last enum variant and
//!   must have exactly one unnamed field of type `goldenscript::Command`.
//!
//! ### Fields: `#[arg]`
//!
//! Variants can be unit, tuple, or struct variants. Unit variants reject all
//! arguments.
//!
//! Fields are processed in declaration order. A fixed positional field consumes
//! the next remaining positional argument. A fixed keyed field looks up its key
//! independently of input position, removes all matching arguments, and parses
//! the last matching value. As a result, positional and keyed arguments can be
//! interleaved in the input, and an optional keyed field can precede a required
//! keyed field in the enum.
//!
//! Each parsed value type must implement [`FromStr`](std::str::FromStr), with
//! an error that implements [`Display`](std::fmt::Display). A `many` field must
//! implement [`FromIterator`], collecting `T` for positional arguments or
//! `(K, V)` for keyed arguments, with both `K` and `V` parsed via `FromStr`.
//! Missing or invalid values are reported for
//! the first field that fails.
//!
//! By default, a field corresponds to a required positional argument, except for the following
//! inferred outer type names:
//!
//! * `Option<T>`: makes the argument optional, i.e. `#[arg(optional)]`.
//!
//! * `Vec<T>`, `VecDeque<T>`, `HashSet<T>`, `BTreeSet<T>`: takes one or more positional
//!   arguments, i.e. `#[arg(pos, many)]`, except for the key/value collections below.
//!
//! * `Vec<(K, V)>`, `HashMap<K, V>`, and `BTreeMap<K, V>`: takes one or more key/value
//!   arguments (equivalent to `#[arg(key, many)]`). A vector preserves input order and duplicate
//!   keys.
//!
//! Inference uses the final type path segment as written, so fully qualified
//! forms such as `std::vec::Vec<T>` are recognized but type aliases are not.
//! Explicit `pos` or `key` options can change the inferred argument kind.
//! Inferred `optional` and `many` behavior cannot be disabled.
//!
//! The `#[arg]` helper attribute accepts:
//!
//! * `pos`: specifies a positional argument. This is the default. Conflicts with `key`.
//!
//! * `key`: specifies a key/value argument instead of a positional argument. Uses the
//!   field name as the key by default, but can be aliased as `key = "name"` (including an empty
//!   name). A later bare `key` option restores the field-name default. Tuple fields require an
//!   alias, while `many` fields reject a key name. Fixed key names must be unique within a variant.
//!   Conflicts with `pos`.
//!
//! * `optional`: allows the argument to be omitted. A fixed `Option<T>` field becomes `None`;
//!   other fixed fields use [`Default::default()`](Default::default). For a `many` field, this
//!   allows an empty collection.
//!
//! * `many`: consumes all remaining arguments of its kind (pos or key) using `FromIterator`. At
//!   least one argument must be provided, unless `optional` is set. Duplicate input keys collected
//!   by a keyed `many` field use the collection's `FromIterator` behavior:
//!   `Vec<(K, V)>` retains every pair in input order, while maps use their usual duplicate-key
//!   behavior.
//!
//! A required positional field cannot be specified after an optional positional field. Fields with
//! `many` must be the last field of the same argument kind, but can be followed by a field of the
//! other kind.
//!
//! Unknown command names, missing or invalid values, and arguments left over
//! after all fields are processed produce conversion errors.
//!
//! ## Argument Processing
//!
//! Arguments can be processed manually via [`Command::args`], or using the
//! [`Command::consume_args()`] helper which simplifies common argument
//! handling. For example:
//!
//! ```
//! # use std::error::Error;
//! # struct Runner;
//! # impl Runner {
//! #   fn send(&self, ids: &[u32], message: &str, retry: bool) -> Result<String, Box<dyn Error>> {
//! #     Ok(String::new())
//! #   }
//! # }
//! #
//! impl goldenscript::Runner for Runner {
//!     type Command = goldenscript::Command;
//!
//!     /// Implement a send command, which sends a string message to a list
//!     /// of nodes, optionally retrying.
//!     ///
//!     /// send [retry=BOOL] MESSAGE ID...
//!     ///
//!     /// Example: send foo 1 2 3
//!     fn run(
//!         &mut self,
//!         command: &goldenscript::Command,
//!         _context: &goldenscript::Context,
//!     ) -> Result<String, Box<dyn Error>> {
//!         if command.name != "send" {
//!             return Err(format!("invalid command {}", command.name).into())
//!         }
//!
//!         let mut args = command.consume_args();
//!
//!         // The first positional argument is a required string message.
//!         let message = args.next_pos().ok_or("message not given")?;
//!
//!         // The remaining positional arguments are numeric node IDs.
//!         let ids: Vec<u32> = std::iter::from_fn(|| args.next_pos())
//!             .map(|value| value.parse())
//!             .collect::<Result<_, _>>()?;
//!         if ids.is_empty() {
//!             return Err("no node IDs given".into())
//!         }
//!
//!         // An optional retry=bool key/value argument can also be given.
//!         let retry: bool =
//!             args.take_key("retry").map(|value| value.parse()).transpose()?.unwrap_or(false);
//!
//!         // Any other arguments that haven't been processed above should error.
//!         args.reject_next()?;
//!
//!         // Execute the send.
//!         self.send(&ids, message, retry)
//!     }
//! }
//! ```
//!
//! ## Managing State
//!
//! The runner is free to manage internal state as desired. If it is stateful,
//! it is recommended to persist state within a single goldenscript (across
//! commands and blocks), but not across goldenscripts since this can be hard to
//! reason about and depend on the execution order of scripts. This is most
//! easily done by instantiating a new runner for each script.
//!
//! Initial state setup should generally be done via explicit setup commands, to
//! make it more discoverable.
//!
//! ## Running All Scripts in a Directory
//!
//! External crates can be used to automatically generate and run individual
//! tests for each goldenscript in a directory. For example, the
//! [`test_each_file`](https://docs.rs/test_each_file/latest/test_each_file/)
//! crate:
//!
//! ```no_run
//! # use std::error::Error;
//! # struct Runner;
//! #
//! # impl goldenscript::Runner for Runner {
//! #     type Command = goldenscript::Command;
//! #
//! #     fn run(
//! #         &mut self,
//! #         _command: &goldenscript::Command,
//! #         _context: &goldenscript::Context,
//! #     ) -> Result<String, Box<dyn Error>> { todo!() }
//! # }
//! use test_each_file::test_each_path;
//!
//! test_each_path! { in "tests/scripts" as scripts => test_goldenscript }
//!
//! fn test_goldenscript(path: &std::path::Path) {
//!     goldenscript::run(&mut Runner, path).unwrap()
//! }
//! ```
//!
//! ## Hooks
//!
//! Runners have various hooks that will be called during script execution:
//! [`Runner::start_script`], [`Runner::end_script`], [`Runner::start_block`],
//! [`Runner::end_block`], [`Runner::start_command`], and
//! [`Runner::end_command`]. These can be used e.g. for initial setup, invariant
//! assertions, or to output the current state.

#![warn(clippy::all)]

mod command;
mod parser;
mod runner;

pub use command::{Argument, ArgumentConsumer, Block, Command, Context};
pub use goldenscript_macros::Command;
pub use runner::{Runner, generate, run};
